// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0RqMLSXfmCUy7RmI7WazYL6NE1_evts',
    appId: '1:784927111208:web:8653c1a16ab28a39ca5d1d',
    messagingSenderId: '784927111208',
    projectId: 'flutter-spotify-18775',
    authDomain: 'flutter-spotify-18775.firebaseapp.com',
    storageBucket: 'flutter-spotify-18775.appspot.com',
    measurementId: 'G-KNJPEPDFZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8DXsB0BiRGBQ55a4mwR7oQD9sbkVQds',
    appId: '1:784927111208:android:5b7ca305d435b737ca5d1d',
    messagingSenderId: '784927111208',
    projectId: 'flutter-spotify-18775',
    storageBucket: 'flutter-spotify-18775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWRczNk9wjZKxOywhRM436FVBbPpR4jM',
    appId: '1:784927111208:ios:b739acc7b0d44866ca5d1d',
    messagingSenderId: '784927111208',
    projectId: 'flutter-spotify-18775',
    storageBucket: 'flutter-spotify-18775.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiWRczNk9wjZKxOywhRM436FVBbPpR4jM',
    appId: '1:784927111208:ios:b739acc7b0d44866ca5d1d',
    messagingSenderId: '784927111208',
    projectId: 'flutter-spotify-18775',
    storageBucket: 'flutter-spotify-18775.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0RqMLSXfmCUy7RmI7WazYL6NE1_evts',
    appId: '1:784927111208:web:c2343d56fc0c5296ca5d1d',
    messagingSenderId: '784927111208',
    projectId: 'flutter-spotify-18775',
    authDomain: 'flutter-spotify-18775.firebaseapp.com',
    storageBucket: 'flutter-spotify-18775.appspot.com',
    measurementId: 'G-BJFLKM8XHG',
  );

}